repo: file
file:
  basePath: "file:///Users/till/updates"
  baseUrl: "http://localhost:8080/static"

assets:
  overrides:
    /static: /Users/till/updates

manta:
  url: "https://eu-ams-1.api.joyentcloud.com"
  updateBasePath: "/yetu/public/gateway/updates/"
  keyFingerprint: "77:ef:4d:a4:1a:33:42:3d:a5:f8:0a:b2:9d:17:67:e4"
  login: yetu
  privateKeyPath: "/Users/till/.ssh/id_rsa"

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.yetu.emscher: DEBUG

    org.hibernate.SQL: ALL

  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      #maxFileSize: 10MB